### ISSUE TITLE
Issues trying to install python-mirobot

### ISSUE THREAD

**Issue by ebretteville** [mrin/domoticz-mirobot-plugin#1]
When trying to issue this command `pip3 install python-mirobo -t .vendors`

I get lots of issues. I posted it in an attached file to not clutter the post. 

I run domoticz on a raspberry pi 2 with raspbian jessie (is it the problem?!).

Thx for your help.
[pbm-pythonmirobot.txt](https://github.com/mrin/domoticz-mirobot-plugin/files/1278237/pbm-pythonmirobot.txt)

**Comment by mrin** [comment]
The same log. Some of issues like "Could not find .egg-info " due local folder installation.
Plugin works?

**Comment by ebretteville** [comment]
I can't add a Xiaomi Mi Robot Vacuum as described here: 

> Now go to Setup -> Hardware in your Domoticz interface and add type with name Xiaomi Mi Robot Vacuum.

Any ideas?!
![2017-09-06 11_00_52-domoticz](https://user-images.githubusercontent.com/3687099/30103383-c8f76566-92f2-11e7-907b-cf5798936db7.png)

**Comment by mrin** [comment]
Which Domoticz version?
Python plugin system works on 3.8153 stable and beta <= 3.8367 only. In latest beta plugin system temporary disabled by developers.

**Comment by mrin** [comment]
If you want to use any python plugin you need stable version of domoticz.

**Comment by ebretteville** [comment]
I reverted it to stable, it worked, sorry
