### ISSUE TITLE
Calling message handler 'onHeartbeat'.

### ISSUE THREAD

**Issue by ebretteville** [mrin/domoticz-mirobot-plugin#2]
Hye,
Don't know what title to give to this issue threzad so I just copy/paste the error message.

Python is intalled, token is found, but it's not working, find below the log from domoticz:
`
2017-09-25 09:48:08.357 (nono) Poll: {"exception": ""}
2017-09-25 09:48:08.357 Error: (nono) Response mirobo-wrapper exception:
2017-09-25 09:48:08.358 PluginSystem: Starting I/O service thread.
2017-09-25 09:48:08.359 (nono) Calling message handler 'onHeartbeat'.
2017-09-25 09:48:30.964 (nono) Poll: {"exception": ""}
`

My xiaomi robot is workinf fine through the mi home app and is called "nono".

Thanks for your help

**Comment by mrin** [comment]
Python-mirobo library does not return good response. Also main lib renamed, so I will update plugin in near future to support latest version.

**Comment by rytilahti** [comment]
The device is not responsive always, but without knowing how does your plugin handle the exceptions the library is throwing I can't really help without further input. I'll close also the https://github.com/rytilahti/python-miio/issues/82 for the time being. As soon as I'm able to get my TODO list for the next release done, I will make a new release :-)
