### ISSUE TITLE
Implement mopping mode.

### ISSUE THREAD

**Issue by Milan1989** [mrin/domoticz-mirobot-plugin#22]
Is there plan to implement mopping mode in this plugin?

**Comment by boscorelly** [comment]
mopping is for v2. Not the vaccum

**Comment by Milan1989** [comment]
But this script works perfectly with gen2 (S50) only this feature is missing.

**Comment by boscorelly** [comment]
s50 is not v2... v2 is styj02ym :)
this plugin was designed for mi robot vacuum
