### ISSUE TITLE
create_connection error since manual Buster update

### ISSUE THREAD

**Issue by ced1442** [mrin/domoticz-mirobot-plugin#29]
Hi, 
I had to update manually my Raspberry pi to Buster with the last domoticz update.. Since this, my Roborock plugin is not working anymore.
Error I get:
`(.env) pi@raspberrypi:~/domoticz/plugins/xiaomi-mirobot $ sudo ./test.py
test: python modules path: ././.env/lib/python3.7/site-packages
test: trying connect to 127.0.0.1:22222
Traceback (most recent call last):
  File "./test.py", line 22, in <module>
    client = socket.create_connection((args.host, args.port))
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`
I've tried to uninstall and re-install python, pip, plugin etc.. I always get this error.

**Comment by Cryonic90** [comment]
I've seen this problem too and found the solution in some packages being too old.
What I've done is update the pip_req.txt to this:
android-backup==0.1.0
asn1crypto==0.23.0
attrs==17.2.0
cffi==1.14.0
click==6.7
construct==2.8.16
cryptography==2.1.3
enum-compat==0.0.2
gevent==1.4.0
greenlet==0.4.15
idna==2.6
msgpack==0.6.2
netifaces==0.10.6
pretty-cron==1.0.2
pycparser==2.18
pycrypto==2.6.1
python-miio==0.3.1
pytz==2017.3
six==1.11.0
typing==3.6.2
zeroconf==0.19.1

Maybe this helps

**Comment by ced1442** [comment]
Many thanks @Cryonic90, it solved the problem.
