### ISSUE TITLE
Support for consumables status

### ISSUE THREAD

**Issue by LemarinelNet** [mrin/domoticz-mirobot-plugin#5]
Hi,

I know that the python miio plugin do support consumables status report.

It would be nice to have some status report in domoticz too, so we could put notification on consumable low level !

**Comment by mrin** [comment]
Hi, 
Ok. How would you like to see these statuses in Domoticz? Each in own virtual device, or 'text' device with json/text formatted data?

**Comment by LemarinelNet** [comment]
I think that a percentage for each consumable would be ok ?
One device for each consumable ?

**Comment by mrin** [comment]
Check new version of plugin 0.1.0. Added care-devices + reset control.
Also check the readme (updated communication with python-miio lib via local server)
