### ISSUE TITLE
Multiple error messages in Domoticz log

### ISSUE THREAD

**Issue by Yevrashka** [mrin/domoticz-mirobot-plugin#7]
Multiple error messages in Domoticz log almost every 10 minutes.
![3](https://user-images.githubusercontent.com/24300377/32596617-2395e9c8-c55e-11e7-86aa-5d404a5f7134.png)

**Comment by mrin** [comment]
Can you please enable Debug in plugin hardware settings and post logs with this error.
My robo with plugin without this issue, so I need to figure out what it is. 
Thank you!

**Comment by Yevrashka** [comment]
It seems that Robot goes offline sometimes.
![6](https://user-images.githubusercontent.com/24300377/32600882-3728b44a-c56b-11e7-8d0f-c0b2df6021bc.png)
![7](https://user-images.githubusercontent.com/24300377/32600884-374a1b3a-c56b-11e7-9939-fdfead1e17bf.png)

**Comment by mrin** [comment]
Seems like your plugin is 0.1.0, please update to 0.1.1

**Comment by Yevrashka** [comment]
nope) it's 0.1.1
![8](https://user-images.githubusercontent.com/24300377/32602926-2b802df6-c572-11e7-8672-f5bd70ca52f1.png)

**Comment by mrin** [comment]
Plugin was not successfully restarted (local server). Solved.
